flowchart LR

%% =====================================================
%% PLANNING
%% =====================================================
    subgraph PLANNING["PLANNING"]
        STEP([Step])
        PLAN["Plan"]
        Variable([Variable])
    end

    style PLANNING fill:#b8a2d4,stroke:#2E5C8A,color:#000
    style STEP fill:#7f59ae,stroke:#2E5C8A,color:#000
    style PLAN fill:#c6a0f5,stroke:#2E5C8A,color:#000
    style Variable fill:#fe7130,stroke:#2E5C8A,color:#000

%% Plan structure

    PLAN -->|hasSubPlan| PLAN
    STEP -->|isDecomposedAsPlan| PLAN

%% Variables
    Variable -->|isInputVarOf| STEP
    Variable -->|isOutputVarOf| STEP




%% =====================================================
%% DEPLOYMENT
%% =====================================================
    subgraph DEPLOYMENT["DEPLOYMENT"]
        Platform([Platform])
        Deployment([Deployment])
        SYS([System])
    end

    style DEPLOYMENT fill:#b0d9e7,stroke:#2E5C8A,color:#000
    style Platform fill:#60c4e4,stroke:#2E5C8A,color:#000
    style Deployment fill:#60c4e4,stroke:#2E5C8A,color:#000
    style SYS fill:#60c4e4,stroke:#2E5C8A,color:#000

    Deployment -->|deployedOnPlatform| Platform
    Deployment -->|deployedSystem| SYS
    Platform -->|hosts| SYS
    SYS -->|implements| STEP


%% =====================================================
%% EXECUTION
%% =====================================================
    subgraph EXECUTION["EXECUTION"]
        Activity([Activity])
        Entity([Entity])
    end


    style EXECUTION fill:#e7a3be,stroke:#2E5C8A,color:#000
    style Activity fill:#e54b89,stroke:#2E5C8A,color:#000
    style Entity fill:#f8b622,stroke:#2E5C8A,color:#000


%% Activity relations
    Activity -->|correspondsToStep| STEP
    Activity -->|madeBySystem| SYS
    Activity -->|used| Entity
    Activity -->|hasResult| Entity
    Activity -->|usedProcedure| PLAN


%% Derivation
    Entity -->|wasDerivedFrom| Entity


%% Entity ↔ Variable
    Entity -->|correspondsToVariable| Variable

