# .github/workflows/auto-publish.yml
name: Publish automatically to /TR
on:
  pull_request: {}
  push:
    branches: [gh-pages]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          SOURCE: ssn/
          W3C_WG_DECISION_URL: https://docs.google.com/document/d/15TBmYhgRjncdd_bvmTKygCD8aIhQo1-Tkg3eOKjYNTw/edit?tab=t.0#heading=h.p4osy2xb7ec
          W3C_BUILD_OVERRIDE: |
            shortName: vocab-ssn-2023
            specStatus: WD
